### ISSUE TITLE
Bit operations for noobs

### ISSUE THREAD

**Issue by dop3j0e** [shackspace/uc-basics#23]
byte/word are made up of bits
in avr, we often need to look at specific bits of a byte
  example: TCCR1A
bitwise logical operations, contrast to boolean ops (& vs &&)
bitwise AND removes bits, bitwise OR sets bits, bitwise XOR flips bits
bit shifts move bit strings where we need them
how to build a mask using shifts
examples
plus lots of illustrations!

**Comment by hdznrrd** [comment]
WIP 5fbe288be4574d0fcf8ab6b9f7c7f80d4d35faf7

**Comment by hdznrrd** [comment]
got it! 09351d3db45e9d10e87e5aecf4687076160811d5
