### ISSUE TITLE
Generate bonus exercises for each module

### ISSUE THREAD

**Issue by dop3j0e** [shackspace/uc-basics#28]
Keep people occupied who finish early.

**Comment by hdznrrd** [comment]
ideas:
- make hardware SPI such a bonus chapter
- soft-pwm as ultra bonus chapter

**Comment by dop3j0e** [comment]
* Store Larson state to EEPROM in button module, start where you left off on boot.

**Comment by dop3j0e** [comment]
Bonus tasks added to all modules but the last, where people may just leave if they want.
